version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./tasks/task:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build: php
    volumes:
      - ./tasks/task:/var/www/html
      - .:/var/www

  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password

  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - "8090:80"
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: password
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-db
#    restart: always
#    ports:
#      - '3306:3306'
#    environment:
#      MYSQL_ROOT_PASSWORD: '123456Root'
#      MYSQL_USER: 'root'
#      MYSQL_PASSWORD: '123456'
#      MYSQL_DATABASE: 'db'
#    volumes:
#      - .tasks/task/application/models/Db.php:/var/lib/mysql
