insert into `users` (`email`, `name`, `gender`, `status`) values 
    ('yul@mail.ru', 'yul', 'female', 'active'),
    ('bor@mail.ru', 'katya', 'female', 'inactive'),
    ('kirill@mail.ru', 'kirill ostap', 'male', 'active'),
    ('misha123@mail.ru', 'mishka', 'female', 'inactive'),
     ('yul1@mail.ru', 'yul1', 'female', 'active'),
    ('bor1@mail.ru', 'katya1', 'female', 'inactive'),
    ('kirill1@mail.ru', 'kirill ostap1', 'male', 'active'),
    ('misha1231@mail.ru', 'mishka1', 'female', 'inactive'),('yul@mail.ru', 'yul', 'female', 'active'),
    ('bor@mail.ru', 'katya', 'female', 'inactive'),
    ('kirill@mail.ru', 'kirill ostap', 'male', 'active'),
    ('misha123@mail.ru', 'mishka', 'female', 'inactive'),
     ('yul1@mail.ru', 'yul1', 'female', 'active'),
    ('bor1@mail.ru', 'katya1', 'female', 'inactive'),
    ('kirill1@mail.ru', 'kirill ostap1', 'male', 'active'),
    ('misha1231@mail.ru', 'mishka1', 'female', 'inactive'),
    ('yul@mail.ru', 'yul', 'female', 'active'),
    ('bor@mail.ru', 'katya', 'female', 'inactive'),
    ('kirill@mail.ru', 'kirill ostap', 'male', 'active'),
    ('misha123@mail.ru', 'mishka', 'female', 'inactive'),
     ('yul1@mail.ru', 'yul1', 'female', 'active'),
    ('bor1@mail.ru', 'katya1', 'female', 'inactive'),
    ('kirill1@mail.ru', 'kirill ostap1', 'male', 'active'),
    ('misha1231@mail.ru', 'mishka1', 'female', 'inactive')